### ISSUE TITLE
swap over current production to the container driven lookup service

### ISSUE THREAD

**Issue by elrayle** [cul-it/qa_server_aws_deploy#7]
Prerequisites:
- [ ] Issue #6 update -prod image 
- [ ] Issue #1 add custom footer
- [ ] Issue #2 add full set of authority files 
- [ ] Issue #3 update env vars 
- [ ] Issue #4 define process for re-deploying the services 
- [ ] Issue #5 setup pingdom to run monitor status page nightly 

Additional Validations:
- [ ] Validate that everything looks like it is running correctly.
- [ ] Rename current lookup service to https://lookup-old.ld4l.org
- [ ] Set container based version to respond at https://lookup.ld4l.org
- [ ] Test that Sinopia still has access
